import Head from "next/head";
import { FC } from "react";
const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Sokchea Leang | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-teal-600 dark:white'>Hello World</h1>
    </>
  );
};
